#!/bin/bash
#
# aliases

# jshint alias
alias jshint=/usr/lib/node_modules/jshint/bin/hint

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ip='curl ifconfig.me'

# enable per default all Warnings, as recommended by JPL C-Coding-Standard D-60411
# removed stupid legacy stuff -Wtraditional
alias gcc='gcc -Wall -pedantic -std=iso9899:1999 -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wconversion'

# fixes "cannot connect to X server " errors
#+ it sets hard DISPLAY to 0.0, exports it and allows local connections.
alias fixX="DISPLAY=:0.0;export DISPLAY;xhost +local:0"
