#!/bin/bash

#
# cleanup
#

# removes a directory
#+ @param $1 the directory
cleanupDirectory () {

    local path="$1";

    if [ -d "$path" ]; then
        rm -r $path;
    fi;
}

# removes some directorys
cleanup () {

    cleanupDirectory "$HOME/.dvdcss";
    cleanupDirectory "$HOME/.covers";
    cleanupDirectory "$HOME/.cache";
}

cleanup

exit 0;
