#! /usr/bin/bash

if [[ ${OSTYPE//[0-9.]/} != 'darwin' ]]; then
   exit 0;
fi

# expand path to include gnu coretuils on os x homebrew if installed
if [ -f /usr/local/opt/coreutils/libexec/gnubin ]; then
    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi
